### ISSUE TITLE
improve http error experience

### ISSUE THREAD

**Issue by codefromthecrypt** [square/exchange#28]
Right now, it is tough to troubleshoot endpoint issues as any cause besides HTTP code seems to not bubble up in the error message. Also, there are retries on 404 which I think aren't helpful.

Here are some suggestions:
* On http error, put the body in the error message or console
* On retry, make sure the last error is visible somewhere
* Only retry 5xx

For example, this is an error if you have a 404 for your OPENAI_HOST. I don't know what the status was, and also can't see the body which would in this case tell me why. For example, in ollama if you don't have the model pulled it returns a 404 saying that.
```
G❯  Looking at this project's last commit, help me change from sam4096/qwen2tools:0.5b to sam4096/qwen2tools:1.5b.
 
Traceback (most recent call last):
  File "/Users/adriancole/oss/goose/.venv/lib/python3.12/site-packages/exchange/exchange.py", line 91, in generate
    message, usage = self.provider.complete(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adriancole/oss/goose/.venv/lib/python3.12/site-packages/exchange/providers/openai.py", line 78, in complete
    response = self._send_request(payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adriancole/oss/goose/.venv/lib/python3.12/site-packages/exchange/providers/retry_with_back_off_decorator.py", line 27, in wrapper
    handle_retry_exhausted(result, max_retries)
  File "/Users/adriancole/oss/goose/.venv/lib/python3.12/site-packages/exchange/providers/retry_with_back_off_decorator.py", line 44, in handle_retry_exhausted
    raise HTTPStatusError(
httpx.HTTPStatusError: Failed after 5.
```

**Comment by codefromthecrypt** [comment]
https://github.com/square/exchange/pull/48 seems to improve this, and possibly solve. Just I don't see assertions on the errors propagated, so not sure if the underlying http bodies are visible or not, particularly on 400 cc @baxen

**Comment by baxen** [comment]
Yes i believe that should do it! Let me know if you find any cases where this isn't raising as expected, or in reverse if you find retry-ables that don't retry correctly

For example with a 401
```
> export OPENAI_API_KEY=invalid
> goose session start
G> howdy
...
httpx.HTTPStatusError: Client error '401 Unauthorized' for url
'https://api.openai.com/v1/chat/completions'
For more information check:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401
{
    "error": {
        "message": "Incorrect API key provided: invalid. You can find your API
key at https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_api_key"
    }
}
```

**Comment by codefromthecrypt** [comment]
cool. I'll close until then, thanks!
